-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 00:44:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estoque` DEFAULT CHARACTER SET utf8 ;
USE `estoque` ;

-- -----------------------------------------------------
-- Table `estoque`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`produtos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `codbarras` VARCHAR(45) NULL DEFAULT NULL,
  `minimo` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`movimentacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quando` DATETIME NOT NULL,
  `produto` INT UNSIGNED NOT NULL,
  `quantidade` INT NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentacao_produtos_idx` (`produto` ASC),
  CONSTRAINT `fk_movimentacao_produtos`
    FOREIGN KEY (`produto`)
    REFERENCES `estoque`.`produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `estoque` ;

-- -----------------------------------------------------
-- Placeholder table for view `estoque`.`estoque_atual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`estoque_atual` (`id` INT, `descricao` INT, `codbarras` INT, `quantidade` INT, `minimo` INT);

-- -----------------------------------------------------
-- View `estoque`.`estoque_atual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estoque`.`estoque_atual`;
USE `estoque`;
CREATE  OR REPLACE VIEW `estoque_atual` AS SELECT m.produto as id, p.descricao, p.codbarras, sum(m.quantidade) as quantidade, p.minimo FROM movimentacao m LEFT JOIN produtos p ON m.produto=p.id GROUP BY m.produto ORDER BY p.descricao;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
